# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

formats: all

build:
  os: ubuntu-22.04
  apt_packages:
    - tree
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - echo "Installing CMake (latest) using pip"
      - pip install cmake
      - cmake --version
      - echo "Configuring CForge project"
      - cmake -S . -B build -DCFORGE_ENABLE_TESTING=OFF -DCFORGE_ENABLE_DOCUMENTATION=ON
      - echo "Patching conf file for ReadTheDocs"
      - mv build/doc.cache/conf.py doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
   configuration: doc/conf.py
