# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import pathlib

# -- Project information ---------------------------------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information
# Values are provided by the build system using CMake's configure_file().

# NOTE This file does not have the usual .in extension for CMake templates files in order to keep
# the VSCode html preview working: the real conf.py is generated inside the build tree while sources
# are stored in the doc/ folder, and even if the lextudio.restructuredtext extension supports
# separate directories for config and sources, it does not seem to work well for the preview engine.
# Consequently the VSCode extension uses this template file to configure Sphinx (without .in ext to
# be a valid Sphinx's conf.py). Be aware that VSCode html preview will have the @variable@ below not
# replaced. For a full featured documentation, please run the provided `doc` target.

project = '@PROJECT_NAME@'
copyright = '@CURRENT_YEAR@, @PROJECT_AUTHOR@'
author = '@PROJECT_AUTHOR@'
version = '@PROJECT_VERSION_MAJOR@.@PROJECT_VERSION_MINOR@'
release = '@PROJECT_VERSION@'

# -- General configuration -------------------------------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# Path where the final conf.py is located:
#   - in ${CMAKE_BINARY_DIR}/doc.cache/ when generating the doc using CMake
#   - in ${CMAKE_SOURCE_DIR}/doc/ when generating the doc on ReadTheDocs.org
file_dir = pathlib.Path(os.path.realpath(__file__)).parent

# Enabled extensions
extensions = [
    'sphinx.ext.intersphinx',
    'sphinxcontrib.moderncmakedomain',
    'sphinxemoji.sphinxemoji'
]

# Do not search source files in these directories
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Warn about references not found
nitpicky = True

# -- Options for HTML output -----------------------------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# Use a theme similar to CMake documentation
html_theme = 'classic'
html_theme_options = {
    'footerbgcolor':    '#00182d',
    'footertextcolor':  '#ffffff',
    'sidebarbgcolor':   '#e4ece8',
    'sidebarbtncolor':  '#00a94f',
    'sidebartextcolor': '#333333',
    'sidebarlinkcolor': '#00a94f',
    'relbarbgcolor':    '#00529b',
    'relbartextcolor':  '#ffffff',
    'relbarlinkcolor':  '#ffffff',
    'bgcolor':          '#ffffff',
    'textcolor':        '#444444',
    'headbgcolor':      '#f2f2f2',
    'headtextcolor':    '#003564',
    'headlinkcolor':    '#3d8ff2',
    'linkcolor':        '#2b63a8',
    'visitedlinkcolor': '#2b63a8',
    'codebgcolor':      '#eeeeee',
    'codetextcolor':    '#333333',
}

# -- Intersphinx configuration ---------------------------------------------------------------------

# Search references in cmake-objects.patched.inv first, then fallback to objects.inv from cmake.org
# cmake-objects.patched.inv is generated by patch-cmake-objects-inv.py
intersphinx_mapping = {
    'cmake.org': ('https://cmake.org/cmake/help/latest', (str(file_dir / 'cmake-objects.patched.inv'), None))
}
