include_guard(GLOBAL)

function(cforge_assert)
    cmake_parse_arguments("ARG" "" "MESSAGE" "CONDITION" ${ARGN})
    if(NOT ARG_CONDITION)
        message(FATAL_ERROR "CONDITION argument is required")
    endif()
    if(NOT (${ARG_CONDITION}))
        set(MESSAGE "Assertion failed!")
        if(ARG_MESSAGE)
            string(APPEND MESSAGE " ${ARG_MESSAGE}")
        endif()
        message(FATAL_ERROR "${MESSAGE}")
    endif()
endfunction()
