name: Build & Tests

on: [push, pull_request]

jobs:

  build:

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install CMake
        run: |
          pip install --upgrade pip
          pip install cmake

      - name: Install LCOV
        uses: hrishikesh-kadam/setup-lcov@v1

      - name: Install Sphinx and extensions
        working-directory: doc
        run: |
          pip3 install -r ./requirements.txt

      - name: Configure
        run: |
          cmake -S . -B build -DCFORGE_ENABLE_DOCUMENTATION=ON

      - name: Build
        run: |
          cmake --build build

      - name: Run tests
        working-directory: build
        run: |
          ctest --output-on-failure --verbose -C Release

      - name: Generate docs
        run: |
          cmake --build build --target doc
